# Generated by Django 3.0.6 on 2021-01-17 10:34

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=2)),
                ('skill', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('post_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1280, 960], upload_to='media/')),
            ],
        ),
    ]
